from enum import Enum
from pydantic import BaseModel, Field
from typing import List


class ProcessingState(str, Enum):
    INITIALIZE = "initialize"
    ANALYZE = "analyze"
    QUERY_DECOMPOSE = "query_decompose"
    RAG = "rag"
    GENERATE_ANSWER = "generate_answer"
    

class Action(str, Enum):
    RETRIEVE = "RETRIEVE"
    ANSWER = "ANSWER"


class ReactOutput(BaseModel): 

    analysis: str = Field(
        default=None, 
        description="The observation made by the agent during the execution of the action."
    )

    action: Action = Field(
        default=None, 
        description="The action taken by the agent in response to the observation (continue looping or return answer)."
    )



class Config(BaseModel): 

    early_stopping : int = Field(
        default=3, 
        description="A flag to indicate if early stopping is enabled (1) or not (0)."
    )

    backbone : str = Field(
        default="gemini-2.0-flash",
        description="The backbone model to be used for the React agent."
    )

    k : int = Field(
        default=3, 
        description="The number of top results to retrieve from the vector store."
    )




class State(BaseModel): 
    

    question: str 

    observation: List[tuple] = Field(
        default=None, 
        description="A list of observations made during the process."
    )

    react_output: ReactOutput = Field(
        default=None, 
        description="The output from the React agent."
    )

    processing_state : ProcessingState = Field(
        default=ProcessingState.INITIALIZE, 
        description="The current state of processing."
    )

    list_queries : List[str] = Field(
        default=[], 
        description="A list of queries generated during the query decomposition step."
    )

    final_answer: str = Field(
        default=None, 
        description="The final answer generated by the system after processing the question and observations."
    )


    config: Config = Field(
        default=Config(), 
        description="Configuration settings for Multi-hop RAG."
    )

    