id: "default"
early_stopping : 3 
k  : 5
backbone : "gpt-4o-mini"
sample_size: 20
random_seed: 23
sampling_method: "in_range"
num_parts : 6
part: 0


hydra:
  job:
    chdir: false  
  output_subdir: null  
  run:
    dir: outputs/${id}
  sweep:
    dir: multirun
    subdir: ${id}